### ISSUE TITLE
Storing the data sent via FIROS in Cygnus

### ISSUE THREAD

**Issue by sejego** [Ikergune/firos#4]
Hi!
I have created a simple publisher/subscriber program in ROS where I send a message every second from one computer to another. FIROS works well, the data is transfered without any troubles and is received by a subscriber on second PC. However, I struggle to save the data in Fiware-Cygnus. I tried creating a device with exactly same parameters that I get everytime I query the sent data through FIROS in Fiware, but it was no use. Is there any other way to keep the data in Cygnus?

Here are the parameters of the sent data.

`    "contextResponses": [
        {
            "contextElement": {
                "attributes": [
                    {
                        "name": "COMMAND",
                        "type": "COMMAND",
                        "value": [
                            "chatter"
                        ]
                    },
                    {
                        "name": "chatter",
                        "type": "std_msgs.msg.String",
                        "value": "{%27firosstamp%27: 1528282566.879989, %27data%27: %27Wake up, Neo 1528282566.88%27}"
                    }
                ],
                "id": "talker",
                "isPattern": "false",
                "type": "ROBOT"
            },
            "statusCode": {
                "code": "200",
                "reasonPhrase": "OK"
            }
        }
    ]
}
`

And here are the attr-s I used to register new device in Cygnus: 

`curl -X POST --url "http://192.168.0.104:4041/iot/devices" -H 'Content-Type: application/json' -H 'Fiware-service: OpenIoT' -H 'Fiware-servicepath: /Robs' -d '{ "devices": [{ "device_id": "talker", "protocol": "IoTA-UL", "entity_name": "talker", "entity_type": "ROBOT", "timezone": "Europe/Rome", "attributes": [ {"object_id": "c", "name": "chatter", "type": "std_msgs.msg.String"}, {"object_id": "CO", "name": "COMMAND", "type": "chatter"} ], "static_attributes": [ {"name": "RobPosition", "type": "string", "value": "Talker1"} ] }] }'`

Thank you in advance.

**Comment by jariza** [comment]
Hi,

if FIROS datas is reaching context broker, Cygnus should be able to pull it. Did you ask Cygnus maintainers? https://catalogue-server.fiware.org/enablers/cygnus

Regards.
